Controllers/CarOwnerGarage/CarOwnerGarageController.cs
using FastFix2._0.Areas.Identity;
using FastFix2._0.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace FastFix2._0.Controllers.CarOwnerGarage
{
    /// <summary>
    /// Controller for CarOwners personal area.
    /// </summary>
    public class CarOwnerGarageController : Controller
    {
        /// <summary>
        /// Returns View of CarOwners personal area.
        /// </summary>
        private readonly FastFixDbContext _db;
        private readonly UserManager<User> _UserManager;

        public CarOwnerGarageController(FastFixDbContext context, UserManager<User> userManager)
        {
            _db = context;
            _UserManager = userManager;
        }

        public IActionResult CarOwnerGarage()
        {
            string user = _UserManager.GetUserId(User);

            var app = from a in _db.NewApplications
                      where a.UserId == user
                      select a;

            return View(app.ToList());
        }

        public IActionResult Answers()
        {

            return View();
        }
    }
}

Controllers/CarOwnerGarage/Garage/MyGarageController.cs
using FastFix2._0.Areas.Garage;
using FastFix2._0.Areas.Identity;
using FastFix2._0.Data;
using FastFix2._0.ViewModels.Garage;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace FastFix2._0.Controllers.CarOwnerGarage.Garage
{
    public class MyGarageController : Controller
    {
        private readonly FastFixDbContext _db;
        private readonly UserManager<User> _UserManager;

        public MyGarageController(FastFixDbContext context, UserManager<User> UserManager)
        {
            _db = context;
            _UserManager = UserManager;
        }

        public IActionResult AddCar() => View(new AddCarViewModel());

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult AddCar(AddCarViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            string user = _UserManager.GetUserId(User);

            var car = new AddCars
            {
                Id = model.Id,
                UserId = user,
                CarModel = model.CarModel,
                Engine = model.Engine,
                Year = model.Year,
                CarPlate = model.CarPlate,
                VinCode = model.VinCode,
                IsVisible = model.IsVisible
            };

            if (model.Id == 0)
            {
                _db.UsersCars.Add(car);
            }

            _db.SaveChanges();

            return RedirectToAction("MyCars", "MyGarage");
        }

        public IActionResult MyCars()
        {
            string userId = _UserManager.GetUserId(User);

            var car = _db.UsersCars.Where(a => a.UserId == userId).ToList();

            if (car != null)
            {
                return View(car);
            }

            return View();
        }
    }
}

Controllers/CarOwnerGarage/MyApplications/MyApplicationsController.cs
using FastFix2._0.Areas.Applications;
using FastFix2._0.Areas.Identity;
using FastFix2._0.Data;
using FastFix2._0.ViewModels.Applications;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace FastFix2._0.Controllers.CarOwnerGarage.MyApplications
{
    public class MyApplicationsController : Controller
    {
        private readonly FastFixDbContext _db;
        private readonly UserManager<User> _UserManager;

        public MyApplicationsController(FastFixDbContext context, UserManager<User> UserManager)
        {
            _db = context;
            _UserManager = UserManager;
        }

        #region Page where carowners can leave new applications for carrepairs.
        public IActionResult New() => View(new CreateApplicationViewModel());

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult New(CreateApplicationViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            string user = _UserManager.GetUserId(User);

            string date = model.RepairFrom.ToShortDateString();

            string Date = date.ToString();

            var app = new NewApplications
            {
                Id = model.Id,
                IssueTitle = model.IssueTitle,
                Car = model.Car,
                RepairFrom = Date,
                RepairTill = model.RepairTill,
                City = model.City,
                TypeOfWork = model.TypeOfWork,
                Description = model.Description,
                UserId = user
            };

            if (model.Id == 0)
            {
                _db.Add(app);
            }

            _db.SaveChanges();

            return RedirectToAction("CarOwnerGarage", "CarOwnerGarage");
        }
        #endregion

        #region Page where carowners look for applicaitons that are waiting for answers from carrepairs.
        public IActionResult Waiting()
        {
            string userId = _UserManager.GetUserId(User);

            var app = from a in _db.NewApplications
                      where userId == a.UserId
                      select a;

            return View(app.ToList());
        }
        #endregion

        #region Method to see answers for concrete applications on Waiting Page.
        public IActionResult LookAnswers(int Id)
        {
            var answers = from a in _db.AnswersForApps
                          where a.AppID == Id
                          select a;

            return View(answers.ToList());
        }
        #endregion

        #region Method to accept proper answer for applicaiton.
        public IActionResult Accept(int AppID)
        {
            var app = _db.NewApplications.Where(a => a.Id == AppID).FirstOrDefault();

            var answer = _db.AnswersForApps.Where(a => a.AppID == AppID).FirstOrDefault();

            ApplicationsInProgress inProgress = new ApplicationsInProgress
            {
                Car = app.Car,
                City = app.City,
                Description = app.Description,
                IssueTitle = app.IssueTitle,
                RepairFrom = app.RepairFrom,
                RepairTill = app.RepairTill,
                TypeOfWork = app.TypeOfWork,
                UserId = app.UserId,
                Message = answer.Message,
                Price = answer.Price,
                CarRepairId = answer.UserId
            };

            _db.ApplicationsInProgress.Add(inProgress);

            _db.NewApplications.Remove(app);

            _db.AnswersForApps.Remove(answer);

            _db.SaveChanges();

            return RedirectToAction("InProgress", "MyApplications");
        }
        #endregion

        #region Page to see applications that are in progress.
        public IActionResult InProgress()
        {
            string getUserId = _UserManager.GetUserId(User);

            var app = _db.ApplicationsInProgress.Where(a => a.UserId == getUserId);

            return View(app.ToList());
        }
        #endregion

        #region Method where carowners can see details of apps that are in progress.
        public IActionResult SeeApp(int Id)
        {
            var app = _db.ApplicationsInProgress.Where(a => a.Id == Id).FirstOrDefault();

            return View(app);
        }
        #endregion

        #region Method which invokes when carowner press finish application, but carrepair didnt finished work.
        public IActionResult FalseFinish()
        {
            return View();
        }
        #endregion

        #region Method which invokes when carowner approve of finished work(after carrepair pressed finished).
        public IActionResult Finish(int Id)
        {

            var App = _db.ApplicationsInProgress.Where(a => a.Id == Id).First();

            if (App.IsFinished == false)
            {
                return RedirectToAction("FalseFinish", "MyApplications");
            }
            if (App.IsFinished == true)
            {
                CompletedApplications completed = new CompletedApplications
                {
                    Car = App.Car,
                    City = App.City,
                    Description = App.Description,
                    IssueTitle = App.IssueTitle,
                    RepairFrom = App.RepairFrom,
                    RepairTill = App.RepairTill,
                    TypeOfWork = App.TypeOfWork,
                    UserId = App.UserId,
                    Message = App.Message,
                    Price = App.Price,
                    CarRepairId = App.CarRepairId
                };

                _db.CompletedApplications.Add(completed);

                _db.ApplicationsInProgress.Remove(App);

                _db.SaveChanges();
            }

            return View();
        }
        #endregion

        #region Page where carowner can see all completed applications.
        public IActionResult Completed()
        {
            string userId = _UserManager.GetUserId(User);

            var getApps = _db.CompletedApplications.Where(a => a.UserId == userId);

            return View(getApps.ToList());
        }
        #endregion
    }
}

Controllers/CarOwnerGarage/OtherFeatures/OtherFeaturesController.cs
using FastFix2._0.Areas.Identity;
using FastFix2._0.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FastFix2._0.Controllers.CarOwnerGarage.OtherFeatures
{
    public class OtherFeaturesController : Controller
    {
        private readonly FastFixDbContext _db;
        private readonly UserManager<User> _UserManager;

        public OtherFeaturesController(FastFixDbContext context, UserManager<User> UserManager)
        {
            _db = context;
            _UserManager = UserManager;
        }

        public IActionResult AccountSettings()
        {

            return View();
        }
    }
}

Views/CarOwnerGarage/Partial/_MainMenu.cshtml
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class="navigation-header">
                <span>My applications</span><i class=" feather icon-minus" data-toggle="tooltip" data-placement="right" data-original-title="Applications"></i>
            </li>
            <li class="nav-item">
                <a asp-controller="MyApplications" asp-action="New"><i class="feather icon-file"></i><span class="menu-title" data-i18n="New">New</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="MyApplications" asp-action="Active"><i class="feather icon-play"></i><span class="menu-title" data-i18n="Active">Active</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="MyApplications" asp-action="Waiting"><i class="feather icon-pause"></i><span class="menu-title" data-i18n="Waiting for response">Waiting for response</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="MyApplications" asp-action="Completed"><i class="feather icon-check-square"></i><span class="menu-title" data-i18n="Completed">Completed</span></a>
            </li>
            <li class="navigation-header">
                <span>Garage</span><i class=" feather icon-minus" data-toggle="tooltip" data-placement="right" data-original-title="Other features"></i>
            </li>
            <li class="nav-item">
                <a asp-controller="Garage" asp-action="MyCars"><i class="feather icon-home"></i><span class="menu-title" data-i18n="My-Car">My cars</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="Garage" asp-action="AddCar"><i class="feather icon-plus"></i><span class="menu-title" data-i18n="Add-Car">Add car</span></a>
            </li>
            <li class="navigation-header">
                <span>Features</span><i class=" feather icon-minus" data-toggle="tooltip" data-placement="right" data-original-title="Job features"></i>
            </li>
            <li class="nav-item">
                <a asp-controller="JobFeatures" asp-action="Chat"><i class="feather icon-message-square"></i><span class="menu-title" data-i18n="Chat">Chat</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="JobFeatures" asp-action="ToDo"><i class="feather icon-check-square"></i><span class="menu-title" data-i18n="To-Do list">To-Do list</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="JobFeatures" asp-action="Calendar"><i class="feather icon-calendar"></i><span class="menu-title" data-i18n="Calendar">Calendar</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="JobFeatures" asp-action="Statistics"><i class="feather icon-bar-chart"></i><span class="menu-title" data-i18n="Statistics">Statistics</span></a>
            </li>
            <li class="navigation-header">
                <span>Other features</span><i class=" feather icon-minus" data-toggle="tooltip" data-placement="right" data-original-title="Other features"></i>
            </li>
            <li class="nav-item">
                <a asp-controller="OtherFeatures" asp-action="AccountSettings"><i class="feather icon-settings"></i><span class="menu-title" data-i18n="Account setting">Account settings</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="OtherFeatures" asp-action="Weather"><i class="feather icon-cloud"></i><span class="menu-title" data-i18n="Weather">Weather</span></a>
            </li>
            <li class="nav-item">
                <a href="#"><i class="feather icon-droplet"></i><span class="menu-title" data-i18n="Theme color">Theme color</span></a>
                <ul class="menu-content">
                    <li>
                        <a class="menu-item" href="#" data-i18n="Primary palette">Standart</a>
                    </li>
                    <li>
                        <a class="menu-item" href="#" data-i18n="Danger palette">Red and white</a>
                    </li>
                    <li>
                        <a class="menu-item" href="#" data-i18n="Success palette">Green</a>
                    </li>
                    <li>
                        <a class="menu-item" href="#" data-i18n="Warning palette">Gradient</a>
                    </li>
                </ul>
            </li>

            <li class="navigation-header">
                <span>Have questions?</span><i class=" feather icon-minus" data-toggle="tooltip" data-placement="right" data-original-title="Others"></i>
            </li>
            <li class="nav-item">
                <a asp-controller="OtherFeatures" asp-action="Support"><i class="feather icon-life-buoy"></i><span class="menu-title" data-i18n="Raise Support">Support</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="OtherFeatures" asp-action="Faq"><i class="feather icon-help-circle"></i><span class="menu-title" data-i18n="FAQ">FAQ</span></a>
            </li>
        </ul>
    </div>
</div>

Views/CarOwnerGarage/Partial/_WaitingForResponseCard.cshtml
<div class="card active-users">
    <div class="card-header border-0">
        <h4 class="card-title">Waiting for response</h4>
        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
        <div class="heading-elements">
            <ul class="list-inline mb-0">
                <li><a data-action="reload"><i class="feather icon-rotate-cw"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="card-content">
        <div id="audience-list-scroll" class="table-responsive position-relative">
            <table class="table">
                <thead>
                    <tr>
                        <th>Car model</th>
                        <th>Repair Date</th>
                        <th>Description</th>
                        <th>Type Of Work</th>
                        <th>More</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-truncate">
                            <div class="avatar avatar-md mr-1">
                                <img class="rounded-circle" src="~/images/portrait/small/avatar-s-11.png" alt="Generic placeholder image">
                            </div>
                            <span class="text-truncate"></span>
                        </td>
                        <td class="align-middle">
                        </td>
                        <td class="align-middle">
                        </td>
                        <td class="align-middle">
                        </td>
                        <td class="align-middle">
                        </td>
                        <td class="align-middle">
                            <button class="btn white bg-amber-lighten-2 bg-amber">See Answers</button>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div id="answer"></div>
        </div>
    </div>
</div>
<script src="~/lib/microsoft/signalr/dist/browser/signalr.min.js"></script>
<script>
        const hubConnection = new signalR.HubConnectionBuilder()
            .withUrl("/Waiting")
            .build();

        hubConnection.on("Send", function (message) {

            let elem = document.createElement("p");
            elem.appendChild(document.createTextNode(message));
            let firstElem = document.getElementById("answer").firstChild;
            document.getElementById("answer").insertBefore(elem, firstElem);
        });

        document.getElementById("sendBtn").addEventListener("click", function (e) {
            let message = document.getElementById("message").value;
            hubConnection.invoke("Send", message, userId);
        });

        hubConnection.start();
</script>